apiVersion: v1
kind: InstallConfig
metadata:
  name: cluster
baseDomain: atg-kni-root-domain.com
platform:
  aws:
    region: us-west-2
    userTags:
      creator: adeodhar
      eco-creator: adeodhar
      eco-email: adeodhar@netap.com
compute: 
  platform:
    aws:
      type: m5.xlarge
