apiVersion: v1
kind: InstallConfig
metadata:
  name: cluster
networking:
  machineCIDR: 192.168.0.0/16
  machineNetwork:
    - cidr: 192.168.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
baseDomain: atg-kni-root-domain.com
platform:
  aws:
    region: us-west-1
